### ISSUE TITLE
Make the modulator and demodulator independed

### ISSUE THREAD

**Issue by KuzmenkoNikita** [LMP88959/PAL-CRT#1]
Hello! You have done a very hard and interesting job! But your demodulator can only be used with a modulator, which is not very natural. it would be much more interesting to have a sequence of analog signal samples at the output of the modulator. And the demodulator would only require it for input. Can you give advice on how to adapt this project for this? I would really like to make the modulator and demodulator independent of each other

**Comment by LMP88959** [comment]
Hi! Thank you. The modulator's output is stored in `struct PAL_CRT -> analog`
The demodulator then uses that `analog` array to convert it to a digital RGB image.

**Comment by KuzmenkoNikita** [comment]
> Hi! Thank you. The modulator's output is stored in `struct PAL_CRT -> analog`
> 
> The demodulator then uses that `analog` array to convert it to a digital RGB image.

Thank you for your reply!

can you please tell me in what form the analog signal is stored? Is it level quantized and time discretized? 

I would like to generate a real analog signal and transmit it over the radio

**Comment by LMP88959** [comment]
The analog signal for a frame is stored as a 1D array where PAL_HRES is the number of samples per horizontal scan line (~64000 ns) and PAL_VRES is the number of scan lines. The samples themselves are stored in signed chars and in IRE units so [-128, 127] range
