### ISSUE TITLE
Ported to Kdenlive

### ISSUE THREAD

**Issue by bigkrimpin** [LMP88959/PAL-CRT#3]
Hello!

I ported your library over to frei0r and it's now able to be used within Kdenlive.
![Screenshot_2023-11-20_01-44-09](https://github.com/LMP88959/PAL-CRT/assets/87676936/c538f181-587d-4114-a47f-442f18947084)
The only problem is that I can't release it because of the license on this repository that is not compatible with the GPL-3.0 (frei0r is licensed under the GPL).
I know this is a lot to ask, but is there maybe a possibility that the license of the repository could be changed to something that is compatible with the GPL?
I'd completely understand if you don't want to do this, then I'll just keep this port for myself.

**Comment by LMP88959** [comment]
The license of both of my *-CRT projects is public domain so you are free to use them however you'd like :)

**Comment by bigkrimpin** [comment]
Ah ok, I saw the license but didn't know that it meant the project was being released into the public domain!
![Screenshot_2023-11-20_15-53-55](https://github.com/LMP88959/PAL-CRT/assets/87676936/8f796189-506c-4cb2-b914-4a2ed58c0833)
One more question, do you want me to put your name in the authors too? If so, which name?

**Comment by LMP88959** [comment]
I would appreciate that, "LMP88959/EMMIR" seems to be the name other people have used so I will go with that. Thank you!

**Comment by bigkrimpin** [comment]
Pushed it to this repo!
https://github.com/bigkrimpin/b1ggiekr1mps

**Comment by LMP88959** [comment]
Awesome thank you!
